name: Deploy Marp Documentation

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      - name: Generate Marp slides
        run: |
          docker run --rm \
            -v $PWD:/home/marp/app/ \
            -e MARP_USER="$(id -u):$(id -g)" \
            -e LANG=$LANG \
            marpteam/marp-cli:v3.2.0 \
            --theme talk/theme.css talk/slides.md --html

          mkdir -p .deploy
          cp talk/slides.html .deploy/index.html
          [ -d talk/figures ] && cp -r talk/figures .deploy/figures
          [ -f talk/theme.css ] && cp talk/theme.css .deploy/theme.css

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages || true
          git checkout -B gh-pages origin/gh-pages || git checkout --orphan gh-pages
          git reset --hard
          rm -rf *

      - name: Deploy to GitHub Pages
        run: |
          cp -r .deploy/* .
          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Deploy Marp slides [skip ci]" || echo "No changes to commit"
          git push origin gh-pages --force